Improve imageslider
scikit-beam/ipywe pull request #54
Opened 2017-09-01 20:41 UTC by yxqd

fixes #53

2017-09-01 20:43 UTC, yxqd commented
Ian, please checkout this branch and run the test_image_slider notebook and play with the widget. Please let me know if you found any bugs. Thanks!

2017-09-01 22:18 UTC, ilumsden requested changes
This worked for Python 2.7, but not for Python 3. Before the pull request is merged, I need you to take a look at #55.

2017-09-07 13:59 UTC, ilumsden approved these changes

2017-09-07 14:01 UTC, ilumsden commented
Ipywidgets 7.0 (available through conda-forge) resolves the issues I was having with running the ImageSlider widget in Python 3. See #55 for more info.

2017-09-07 14:01 UTC, merged